### ISSUE TITLE
Unwanted indentation after import statements

### ISSUE THREAD

**Issue by codewriter3000** [kishmakov/mojo-at-jetbrains#5]
When I hit enter to start a new line after a basic import statement like in:
```py
from python import socket

```
, I get an automatic indent which I don't think that I should be getting.

**Comment by kishmakov** [comment]
Thanks for the report! I in the process of polishing logic in this regard.

**Comment by kishmakov** [comment]
Fixed in version `0.1.4` (it is under review now).
