### ISSUE TITLE
The plugin reports an error when using key parameters

### ISSUE THREAD

**Issue by text-adi** [kishmakov/mojo-at-jetbrains#8]
The following code looks to be working. Mojo runs it successfully. In the case of the plugin, an error occurs.
To reproduce the error, you need to pass the key parameters after the variable parameters.

Code:
```
fn test(*args: Int, another_value: Int = 1) -> Int:
    return another_value

fn main():
    print(test(99, another_value=2))

```

Error:
![image](https://github.com/kishmakov/mojo-at-jetbrains/assets/68295403/f384fc11-7695-44a8-8380-808781d3b404)

The result of the code execution:
```
(base) root@693d2a8db564:/code# mojo test.mojo 
2
```

Mojo documentation:
https://docs.modular.com/mojo/manual/functions#positional-only-and-keyword-only-arguments

**Comment by kishmakov** [comment]
Thank you for pointing out the problem, Oleksii! It is fixed in version `0.1.6`, which is under review before publication. Hopefully will be available on Monday evening (11.03.2024).
