### ISSUE TITLE
There is no support for separating position and key arguments

### ISSUE THREAD

**Issue by text-adi** [kishmakov/mojo-at-jetbrains#9]
The following code will be executed by mojo without any problems. The plugin reports an error:
`Non-variadic argument follows variadic argumen`

Code:
```
fn test(args: Int, *, another_value: Int) -> Int:
    return another_value

fn main():
    print(test(99, another_value=1))
```

Error:
![image](https://github.com/kishmakov/mojo-at-jetbrains/assets/68295403/f3401d57-4bfa-4590-be16-12c9fb6192a8)

The result of the code execution:
```
(base) root@693d2a8db564:/code# mojo test.mojo 
1
```

**Comment by kishmakov** [comment]
Thank you for noticing! 

I missed this case for some reasons. It is handled properly in version `0.1.6`, which is under review before publication. Hopefully will be available on Monday evening (11.03.2024).
